export const users = [
    {
      id: 1,
      name: "Alice",
      address: "123 Main St, Springfield",
      customerId: "CUST-1234",
      email: "alice@gmail.com",
      phone: "555-1234",
      loyaltyTier: "Silver",
      segment: "Sleepy Customer",
      lifetimeValue: "$1M",
      propensityToPurchase: "75%",
      engagementScore: "80%",
    },
    {
      id: 2,
      name: "Bob",
      address: "456 Elm St, Rivertown",
      customerId: "CUST-5678",
      email: "bob@gmail.com",
      phone: "555-5678",
      loyaltyTier: "Gold",
      segment: "Active Customer",
      lifetimeValue: "$750K",
      propensityToPurchase: "85%",
      engagementScore: "90%",
    },
    {
      id: 3,
      name: "Charlie",
      address: "789 Oak St, Hillview",
      customerId: "CUST-91011",
      email: "charlie@gmail.com",
      phone: "555-9101",
      loyaltyTier: "Bronze",
      segment: "New Customer",
      lifetimeValue: "$100K",
      propensityToPurchase: "50%",
      engagementScore: "65%",
    },
    {
      id: 4,
      name: "Rach Sharma",
      address: "12 Baker St, London",
      customerId: "CUST-1213",
      email: "rach.sharma@gmail.com",
      phone: "555-0012",
      loyaltyTier: "Platinum",
      segment: "High-Value Customer",
      lifetimeValue: "$2M",
      propensityToPurchase: "95%",
      engagementScore: "98%",
    },
    {
      id: 5,
      name: "John Doe",
      address: "88 Main Ave, Sunnyvale",
      customerId: "CUST-1415",
      email: "john.doe@gmail.com",
      phone: "555-0025",
      loyaltyTier: "Silver",
      segment: "Moderate Spender",
      lifetimeValue: "$500K",
      propensityToPurchase: "65%",
      engagementScore: "70%",
    },
    {
      id: 6,
      name: "Jane Smith",
      address: "200 Maple Dr, Greenfield",
      customerId: "CUST-1617",
      email: "jane.smith@gmail.com",
      phone: "555-0036",
      loyaltyTier: "Gold",
      segment: "Frequent Buyer",
      lifetimeValue: "$800K",
      propensityToPurchase: "80%",
      engagementScore: "85%",
    },
    {
      id: 7,
      name: "Alex Johnson",
      address: "55 Broadway, New York",
      customerId: "CUST-1819",
      email: "alex.johnson@gmail.com",
      phone: "555-0047",
      loyaltyTier: "Platinum",
      segment: "VIP",
      lifetimeValue: "$3M",
      propensityToPurchase: "90%",
      engagementScore: "95%",
    },
    {
      id: 8,
      name: "Emily Davis",
      address: "77 Sunset Blvd, Los Angeles",
      customerId: "CUST-2021",
      email: "emily.davis@gmail.com",
      phone: "555-0058",
      loyaltyTier: "Bronze",
      segment: "Occasional Buyer",
      lifetimeValue: "$150K",
      propensityToPurchase: "40%",
      engagementScore: "50%",
    },
    {
      id: 9,
      name: "Chris Brown",
      address: "34 Lake St, Chicago",
      customerId: "CUST-2223",
      email: "chris.brown@gmail.com",
      phone: "555-0069",
      loyaltyTier: "Gold",
      segment: "Frequent Buyer",
      lifetimeValue: "$900K",
      propensityToPurchase: "75%",
      engagementScore: "80%",
    },
    {
      id: 10,
      name: "Taylor White",
      address: "16 River Rd, Miami",
      customerId: "CUST-2425",
      email: "taylor.white@gmail.com",
      phone: "555-0070",
      loyaltyTier: "Silver",
      segment: "Moderate Spender",
      lifetimeValue: "$600K",
      propensityToPurchase: "60%",
      engagementScore: "75%",
    },
  ];
  